### ISSUE TITLE
Why Spring?

### ISSUE THREAD

**Issue by jmrapp1** [ramswaroop/botkit#10]
Why not completely separate this from Spring and allow it to be used in any form of Java application (desktop, android, enterprise, etc)?

I was going to take a crack at implementing the Facebook bot until I realized the base of this library is developed on Spring which I am not fully familiar with.

**Comment by ramswaroop** [comment]
Hi,

Thanks for reaching out. You can think this framework as your backend which resides in the cloud/server and you can have any kind of __client__ application (desktop/android/iOS etc) interact with it.

It would be a bad design if you include this in your app which is just a client. Its purpose should be only to provide an interface to your users to access your bot. Hope I make sense here.

This framework is of course made with spring-boot but you __do not__ need to know spring in order to use BotKit. You can just write code using plain java.

**Comment by jmrapp1** [comment]
Ahh OK yes that makes obvious sense, not sure why I didn't think of that before asking! Yes I understand that you don't need to understand Spring to use the actual bot itself, but I was going to work on a Facebook Bot implementation which would require knowledge in Spring to tie into your framework. I'll read through your code and learn as I go to get an understanding of what's going on.
